/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2025-10-17 15:44:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class catalogo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/Santiago/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld", Long.valueOf(1664471478000L));
    _jspx_dependants.put("jar:file:/C:/Users/Santiago/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664471478000L));
    _jspx_dependants.put("/jsp/includes/navbar.jspf", Long.valueOf(1760680707525L));
    _jspx_dependants.put("file:/C:/Users/Santiago/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1760639429198L));
    _jspx_dependants.put("/jsp/includes/footer.jspf", Long.valueOf(1760677104278L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <meta name=\"description\" content=\"Catálogo de productos tecnológicos - NM Telecom\">\n");
      out.write("        <title>Catálogo de Productos | NM Telecom S.A.C.</title>\n");
      out.write("\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\" />\n");
      out.write("\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/custom-style.css\">\n");
      out.write("\n");
      out.write("        <style>\n");
      out.write("            /* ============================================\n");
      out.write("               ESTILOS ESPECÍFICOS DEL CATÁLOGO\n");
      out.write("               ============================================ */\n");
      out.write("\n");
      out.write("            /* Hero Section */\n");
      out.write("            .btn-icon-cart {\n");
      out.write("    width: 45px;\n");
      out.write("    padding: 0.5rem;\n");
      out.write("}\n");
      out.write("            .hero-section {\n");
      out.write("                background: linear-gradient(135deg, var(--nm-dark) 0%, var(--nm-dark-lighter) 100%);\n");
      out.write("                padding: 4rem 0 3rem;\n");
      out.write("                margin-bottom: 3rem;\n");
      out.write("                position: relative;\n");
      out.write("                overflow: hidden;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .hero-section::before {\n");
      out.write("                content: '';\n");
      out.write("                position: absolute;\n");
      out.write("                top: 0;\n");
      out.write("                left: 0;\n");
      out.write("                right: 0;\n");
      out.write("                bottom: 0;\n");
      out.write("                background: url('data:image/svg+xml,<svg width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\"><defs><pattern id=\"grid\" width=\"100\" height=\"100\" patternUnits=\"userSpaceOnUse\"><path d=\"M 100 0 L 0 0 0 100\" fill=\"none\" stroke=\"rgba(43,165,160,0.05)\" stroke-width=\"1\"/></pattern></defs><rect width=\"100%\" height=\"100%\" fill=\"url(%23grid)\"/></svg>');\n");
      out.write("                opacity: 0.3;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .hero-content {\n");
      out.write("                position: relative;\n");
      out.write("                z-index: 1;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .page-title {\n");
      out.write("                font-weight: 300;\n");
      out.write("                letter-spacing: 1px;\n");
      out.write("                color: var(--nm-white);\n");
      out.write("                margin-bottom: 0.5rem;\n");
      out.write("                font-size: 2.75rem;\n");
      out.write("                text-shadow: 0 2px 4px rgba(0,0,0,0.1);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .page-subtitle {\n");
      out.write("                color: var(--nm-accent);\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("                font-weight: 400;\n");
      out.write("                opacity: 0.95;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            /* Product Cards */\n");
      out.write("            .product-card {\n");
      out.write("                position: relative;\n");
      out.write("                height: 100%;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .product-image-wrapper {\n");
      out.write("                position: relative;\n");
      out.write("                overflow: hidden;\n");
      out.write("                border-radius: 16px 16px 0 0;\n");
      out.write("                background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .stock-badge {\n");
      out.write("                position: absolute;\n");
      out.write("                top: 1rem;\n");
      out.write("                right: 1rem;\n");
      out.write("                background: rgba(255, 255, 255, 0.95);\n");
      out.write("                backdrop-filter: blur(10px);\n");
      out.write("                padding: 0.4rem 0.8rem;\n");
      out.write("                border-radius: 20px;\n");
      out.write("                font-size: 0.75rem;\n");
      out.write("                font-weight: 600;\n");
      out.write("                color: var(--nm-accent);\n");
      out.write("                box-shadow: var(--shadow-sm);\n");
      out.write("                z-index: 2;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .stock-badge.out-of-stock {\n");
      out.write("                background: rgba(220, 53, 69, 0.95);\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .product-name {\n");
      out.write("                min-height: 3rem;\n");
      out.write("                font-weight: 600;\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("                line-height: 1.4;\n");
      out.write("                color: var(--nm-dark);\n");
      out.write("                margin-bottom: 0.5rem;\n");
      out.write("                display: -webkit-box;\n");
      out.write("                -webkit-line-clamp: 2;\n");
      out.write("                -webkit-box-orient: vertical;\n");
      out.write("                overflow: hidden;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .product-category {\n");
      out.write("                display: inline-block;\n");
      out.write("                background: var(--nm-accent-light);\n");
      out.write("                color: var(--nm-accent);\n");
      out.write("                padding: 0.25rem 0.75rem;\n");
      out.write("                border-radius: 20px;\n");
      out.write("                font-size: 0.8rem;\n");
      out.write("                font-weight: 500;\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .product-price {\n");
      out.write("                color: var(--nm-accent);\n");
      out.write("                font-size: 1.75rem;\n");
      out.write("                font-weight: 700;\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("                letter-spacing: -0.5px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .price-label {\n");
      out.write("                font-size: 0.8rem;\n");
      out.write("                color: var(--nm-medium-gray);\n");
      out.write("                font-weight: 400;\n");
      out.write("                display: block;\n");
      out.write("                margin-bottom: 0.25rem;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            /* Empty State */\n");
      out.write("            .empty-state {\n");
      out.write("                text-align: center;\n");
      out.write("                padding: 5rem 2rem;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .empty-state-icon {\n");
      out.write("                font-size: 5rem;\n");
      out.write("                color: var(--nm-gray);\n");
      out.write("                margin-bottom: 1.5rem;\n");
      out.write("                opacity: 0.5;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .empty-state-title {\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("                color: var(--nm-dark);\n");
      out.write("                margin-bottom: 0.5rem;\n");
      out.write("                font-weight: 600;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .empty-state-text {\n");
      out.write("                color: var(--nm-medium-gray);\n");
      out.write("                font-size: 1rem;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            /* Loading Animation */\n");
      out.write("            .loading-spinner {\n");
      out.write("                display: inline-block;\n");
      out.write("                width: 40px;\n");
      out.write("                height: 40px;\n");
      out.write("                border: 4px solid var(--nm-gray);\n");
      out.write("                border-top-color: var(--nm-accent);\n");
      out.write("                border-radius: 50%;\n");
      out.write("                animation: spin 1s linear infinite;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @keyframes spin {\n");
      out.write("                to {\n");
      out.write("                    transform: rotate(360deg);\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            /* Responsive Adjustments */\n");
      out.write("            @media (max-width: 768px) {\n");
      out.write("                .hero-section {\n");
      out.write("                    padding: 3rem 0 2rem;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                .page-title {\n");
      out.write("                    font-size: 2rem;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                .page-subtitle {\n");
      out.write("                    font-size: 1rem;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <!-- Navbar -->\n");
      out.write("        ");
      out.write("\n");
      out.write("<style>\n");
      out.write("    /* ============================================\n");
      out.write("      ESTILOS GENERALES Y CART-BADGE\n");
      out.write("      ============================================ */\n");
      out.write("    :root {\n");
      out.write("        --nm-dark: #0b2f4f; /* Azul Oscuro (Primario) */\n");
      out.write("        --nm-accent: #38a798; /* Cian/Verde (Acento) */\n");
      out.write("    }\n");
      out.write("    .navbar {\n");
      out.write("        background-color: white; /* Fondo blanco */\n");
      out.write("        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);\n");
      out.write("    }\n");
      out.write("    .navbar-brand, .nav-link {\n");
      out.write("        color: var(--nm-dark) !important;\n");
      out.write("        font-weight: 500;\n");
      out.write("        transition: color 0.2s;\n");
      out.write("    }\n");
      out.write("    .navbar-brand:hover, .nav-link:hover {\n");
      out.write("        color: var(--nm-accent) !important;\n");
      out.write("    }\n");
      out.write("    .cart-badge {\n");
      out.write("        position: absolute;\n");
      out.write("        top: -8px;\n");
      out.write("        right: -8px;\n");
      out.write("        background: linear-gradient(135deg, #dc3545 0%, #c82333 100%);\n");
      out.write("        color: white;\n");
      out.write("        border-radius: 50%;\n");
      out.write("        width: 20px;\n");
      out.write("        height: 20px;\n");
      out.write("        display: flex;\n");
      out.write("        align-items: center;\n");
      out.write("        justify-content: center;\n");
      out.write("        font-size: 0.7rem;\n");
      out.write("        font-weight: 700;\n");
      out.write("        box-shadow: 0 2px 8px rgba(220, 53, 69, 0.4);\n");
      out.write("        z-index: 10;\n");
      out.write("    }\n");
      out.write("    .nav-link.cart-link {\n");
      out.write("        position: relative;\n");
      out.write("    }\n");
      out.write("    /* Estilo para el nombre de usuario */\n");
      out.write("    .user-info {\n");
      out.write("        font-weight: 600;\n");
      out.write("        color: var(--nm-accent) !important;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg sticky-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\n");
      out.write("            <i class=\"fas fa-hexagon\" style=\"color: var(--nm-accent);\"></i> NM Telecom\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" \n");
      out.write("                data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" \n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\n");
      out.write("                        <i class=\"fas fa-home\"></i> Inicio\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/catalogo\">\n");
      out.write("                        <i class=\"fas fa-box-open\"></i> Productos\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/servicios\">\n");
      out.write("                        <i class=\"fas fa-cogs\"></i> Servicios\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contacto\">\n");
      out.write("                        <i class=\"fas fa-envelope\"></i> Contacto\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link cart-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/carrito\">\n");
      out.write("                        <i class=\"fas fa-shopping-cart\"></i> Carrito\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Toast Container -->\n");
      out.write("        <div class=\"toast-container position-fixed top-0 end-0 p-3\" style=\"z-index: 9999; margin-top: 70px;\">\n");
      out.write("            <div id=\"cartToast\" class=\"toast\" role=\"alert\" aria-live=\"assertive\" aria-atomic=\"true\">\n");
      out.write("                <div class=\"toast-header\">\n");
      out.write("                    <i class=\"fas fa-shopping-cart me-2\" id=\"toast-icon\"></i>\n");
      out.write("                    <strong class=\"me-auto\" id=\"toast-title\">Carrito</strong>\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"toast\"></button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"toast-body\" id=\"toast-message\"></div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Hero Section -->\n");
      out.write("        <section class=\"hero-section\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"hero-content text-center\">\n");
      out.write("                    <h1 class=\"page-title\">Elige el producto a tu necesidad</h1>\n");
      out.write("                    <p class=\"page-subtitle\">Tecnología de vanguardia con la mejor calidad y precio</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <!-- Catalog Section -->\n");
      out.write("        <main class=\"container mb-5\">\n");
      out.write("            <div class=\"row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4\">\n");
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("                <!-- Empty State -->\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </main>\n");
      out.write("\n");
      out.write("        <!-- Footer Premium -->\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* ============================================\r\n");
      out.write("       ESTILOS DEL FOOTER\r\n");
      out.write("       ============================================ */\r\n");
      out.write("    \r\n");
      out.write("    .footer-premium {\r\n");
      out.write("        background: linear-gradient(135deg, var(--nm-dark) 0%, #162d3e 100%);\r\n");
      out.write("        color: var(--nm-white);\r\n");
      out.write("        padding: 3rem 0 1.5rem;\r\n");
      out.write("        margin-top: 5rem;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-premium::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        height: 1px;\r\n");
      out.write("        background: linear-gradient(90deg, transparent, var(--nm-accent), transparent);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-brand {\r\n");
      out.write("        font-size: 1.75rem;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        color: var(--nm-white);\r\n");
      out.write("        margin-bottom: 0.5rem;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-brand i {\r\n");
      out.write("        color: var(--nm-accent);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-tagline {\r\n");
      out.write("        color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("        font-style: italic;\r\n");
      out.write("        margin-bottom: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-section-title {\r\n");
      out.write("        color: var(--nm-accent);\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        margin-bottom: 1rem;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        letter-spacing: 1px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-link {\r\n");
      out.write("        color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        display: block;\r\n");
      out.write("        padding: 0.4rem 0;\r\n");
      out.write("        transition: var(--transition);\r\n");
      out.write("        font-size: 0.95rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-link:hover {\r\n");
      out.write("        color: var(--nm-accent);\r\n");
      out.write("        padding-left: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-contact-item {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: start;\r\n");
      out.write("        gap: 0.75rem;\r\n");
      out.write("        margin-bottom: 1rem;\r\n");
      out.write("        color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-contact-item i {\r\n");
      out.write("        color: var(--nm-accent);\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        margin-top: 0.2rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .social-links {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 1rem;\r\n");
      out.write("        margin-top: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .social-link {\r\n");
      out.write("        width: 45px;\r\n");
      out.write("        height: 45px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        background: rgba(43, 165, 160, 0.15);\r\n");
      out.write("        border: 2px solid rgba(43, 165, 160, 0.3);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        color: var(--nm-accent);\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        transition: var(--transition);\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .social-link:hover {\r\n");
      out.write("        background: var(--nm-accent);\r\n");
      out.write("        color: white;\r\n");
      out.write("        transform: translateY(-3px);\r\n");
      out.write("        box-shadow: 0 5px 15px rgba(43, 165, 160, 0.4);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-bottom {\r\n");
      out.write("        margin-top: 2.5rem;\r\n");
      out.write("        padding-top: 1.5rem;\r\n");
      out.write("        border-top: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-bottom p {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-bottom a {\r\n");
      out.write("        color: var(--nm-accent);\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        transition: var(--transition);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer-bottom a:hover {\r\n");
      out.write("        color: var(--nm-white);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* Responsive */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .footer-premium {\r\n");
      out.write("            padding: 2rem 0 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .social-links {\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer-premium\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <!-- Company Info -->\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"footer-brand\">\r\n");
      out.write("                    <i class=\"fas fa-hexagon\"></i>\r\n");
      out.write("                    NM Telecom\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"footer-tagline\">Innovación y eficiencia en cada solución</p>\r\n");
      out.write("                <p style=\"color: rgba(255, 255, 255, 0.7); font-size: 0.9rem; line-height: 1.6;\">\r\n");
      out.write("                    Líderes en tecnología y telecomunicaciones, brindando soluciones \r\n");
      out.write("                    integrales para empresas y particulares con la mejor calidad del mercado.\r\n");
      out.write("                </p>\r\n");
      out.write("                <div class=\"social-links\">\r\n");
      out.write("                    <a href=\"https://www.facebook.com/nmtelecom\" class=\"social-link\" \r\n");
      out.write("                       target=\"_blank\" aria-label=\"Facebook\">\r\n");
      out.write("                        <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"https://www.instagram.com/nmtelecom\" class=\"social-link\" \r\n");
      out.write("                       target=\"_blank\" aria-label=\"Instagram\">\r\n");
      out.write("                        <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"https://wa.me/51999999999\" class=\"social-link\" \r\n");
      out.write("                       target=\"_blank\" aria-label=\"WhatsApp\">\r\n");
      out.write("                        <i class=\"fab fa-whatsapp\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"tel:+51999999999\" class=\"social-link\" aria-label=\"Teléfono\">\r\n");
      out.write("                        <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Quick Links -->\r\n");
      out.write("            <div class=\"col-lg-2 col-md-6\">\r\n");
      out.write("                <h6 class=\"footer-section-title\">Enlaces</h6>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"footer-link\">Inicio</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/catalogo\" class=\"footer-link\">Productos</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/servicios\" class=\"footer-link\">Servicios</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/nosotros\" class=\"footer-link\">Nosotros</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contacto\" class=\"footer-link\">Contacto</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Services -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <h6 class=\"footer-section-title\">Servicios</h6>\r\n");
      out.write("                <a href=\"#\" class=\"footer-link\">Venta de Equipos</a>\r\n");
      out.write("                <a href=\"#\" class=\"footer-link\">Soporte Técnico</a>\r\n");
      out.write("                <a href=\"#\" class=\"footer-link\">Instalaciones</a>\r\n");
      out.write("                <a href=\"#\" class=\"footer-link\">Mantenimiento</a>\r\n");
      out.write("                <a href=\"#\" class=\"footer-link\">Consultoría IT</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Contact Info -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <h6 class=\"footer-section-title\">Contacto</h6>\r\n");
      out.write("                <div class=\"footer-contact-item\">\r\n");
      out.write("                    <i class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                    <span>Jirón las Begonias 225<br>San Isidro, Lima - Perú</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-contact-item\">\r\n");
      out.write("                    <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("                    <a href=\"mailto:info@nmtelecom.pe\" style=\"color: inherit; text-decoration: none;\">\r\n");
      out.write("                        info@nmtelecom.pe\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-contact-item\">\r\n");
      out.write("                    <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                    <a href=\"tel:+51999999999\" style=\"color: inherit; text-decoration: none;\">\r\n");
      out.write("                        +51 999 999 999\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-contact-item\">\r\n");
      out.write("                    <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                    <span>Lun - Vie: 9:00 AM - 6:00 PM<br>Sábados: 9:00 AM - 1:00 PM</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Footer Bottom -->\r\n");
      out.write("        <div class=\"footer-bottom\">\r\n");
      out.write("            <p>\r\n");
      out.write("                &copy; 2020 - 2025 <strong>NM Telecom S.A.C.</strong> | Todos los derechos reservados | \r\n");
      out.write("                <a href=\"#\">Términos y Condiciones</a> | \r\n");
      out.write("                <a href=\"#\">Política de Privacidad</a>\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    // ===========================================\n");
      out.write("    // Función para actualizar badge del carrito\n");
      out.write("    // ===========================================\n");
      out.write("    function updateCartBadge(count) {\n");
      out.write("        let badge = $('#cart-badge-count');\n");
      out.write("        if (count > 0) {\n");
      out.write("            badge.text(count).removeClass('d-none');\n");
      out.write("        } else {\n");
      out.write("            badge.text(0).addClass('d-none');\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // ===========================================\n");
      out.write("    // Función para mostrar Toast\n");
      out.write("    // ===========================================\n");
      out.write("    function showToast(message, type = 'success') {\n");
      out.write("        const toastEl = $('#cartToast');\n");
      out.write("        const toastIcon = $('#toast-icon');\n");
      out.write("        const toastTitle = $('#toast-title');\n");
      out.write("        const toastMessage = $('#toast-message');\n");
      out.write("        \n");
      out.write("        toastMessage.text(message);\n");
      out.write("        \n");
      out.write("        // Cambiar el ícono y título según el tipo\n");
      out.write("        toastIcon.removeClass('fa-shopping-cart fa-exclamation-triangle fa-times-circle text-success text-danger text-warning');\n");
      out.write("        \n");
      out.write("        if (type === 'success') {\n");
      out.write("            toastIcon.addClass('fa-shopping-cart text-success');\n");
      out.write("            toastTitle.text('¡Éxito!');\n");
      out.write("        } else if (type === 'error') {\n");
      out.write("            toastIcon.addClass('fa-times-circle text-danger');\n");
      out.write("            toastTitle.text('Error');\n");
      out.write("        } else if (type === 'warning') {\n");
      out.write("            toastIcon.addClass('fa-exclamation-triangle text-warning');\n");
      out.write("            toastTitle.text('Aviso');\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        const toast = new bootstrap.Toast(toastEl);\n");
      out.write("        toast.show();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // ===========================================\n");
      out.write("    // Función para agregar al carrito (AJAX)\n");
      out.write("    // ===========================================\n");
      out.write("    function agregarAlCarrito(idProducto, btnElement) {\n");
      out.write("        const $btn = $(btnElement);\n");
      out.write("        const originalHtml = $btn.html();\n");
      out.write("        \n");
      out.write("        // Deshabilitar botón y mostrar loading\n");
      out.write("        $btn.prop('disabled', true);\n");
      out.write("        if ($btn.hasClass('btn-comprar')) {\n");
      out.write("            $btn.html('<span class=\"spinner-border spinner-border-sm\" role=\"status\"></span> Agregando...');\n");
      out.write("        } else {\n");
      out.write("            $btn.html('<span class=\"spinner-border spinner-border-sm\" role=\"status\"></span>');\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        $.ajax({\n");
      out.write("            type: 'POST',\n");
      out.write("            url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/carrito',\n");
      out.write("            data: {\n");
      out.write("                idProducto: idProducto,\n");
      out.write("                accion: 'agregar'\n");
      out.write("            },\n");
      out.write("            dataType: 'json',\n");
      out.write("            success: function(response) {\n");
      out.write("                if (response.success) {\n");
      out.write("                    // Actualizar badge del carrito\n");
      out.write("                    updateCartBadge(response.count);\n");
      out.write("                    \n");
      out.write("                    // Mostrar toast de éxito\n");
      out.write("                    showToast(response.message || 'Producto agregado al carrito', 'success');\n");
      out.write("                } else {\n");
      out.write("                    // Verificar si requiere login\n");
      out.write("                    if (response.requireLogin) {\n");
      out.write("                        showToast('Debe iniciar sesión para agregar productos', 'warning');\n");
      out.write("                        setTimeout(() => {\n");
      out.write("                            window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login';\n");
      out.write("                        }, 1500);\n");
      out.write("                    } else {\n");
      out.write("                        showToast(response.message || 'No se pudo agregar al carrito', 'error');\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            error: function() {\n");
      out.write("                showToast('Error de conexión con el servidor', 'error');\n");
      out.write("            },\n");
      out.write("            complete: function() {\n");
      out.write("                // Restaurar botón\n");
      out.write("                $btn.prop('disabled', false);\n");
      out.write("                $btn.html(originalHtml);\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // ===========================================\n");
      out.write("    // Document Ready\n");
      out.write("    // ===========================================\n");
      out.write("    $(document).ready(function() {\n");
      out.write("        // Smooth scroll\n");
      out.write("        document.querySelectorAll('a[href^=\"#\"]').forEach(anchor => {\n");
      out.write("            anchor.addEventListener('click', function(e) {\n");
      out.write("                e.preventDefault();\n");
      out.write("                const target = document.querySelector(this.getAttribute('href'));\n");
      out.write("                if (target) {\n");
      out.write("                    target.scrollIntoView({behavior: 'smooth', block: 'start'});\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // Animación de entrada para las cards\n");
      out.write("        const observer = new IntersectionObserver((entries) => {\n");
      out.write("            entries.forEach(entry => {\n");
      out.write("                if (entry.isIntersecting) {\n");
      out.write("                    entry.target.style.opacity = '1';\n");
      out.write("                    entry.target.style.transform = 'translateY(0)';\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }, {threshold: 0.1});\n");
      out.write("\n");
      out.write("        document.querySelectorAll('.card').forEach(card => {\n");
      out.write("            card.style.opacity = '0';\n");
      out.write("            card.style.transform = 'translateY(20px)';\n");
      out.write("            card.style.transition = 'opacity 0.5s ease, transform 0.5s ease';\n");
      out.write("            observer.observe(card);\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                    ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /jsp/includes/navbar.jspf(83,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.usuarioLogeado}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        ");
          out.write("\n");
          out.write("                        <li class=\"nav-item dropdown\">\n");
          out.write("                            <a class=\"nav-link dropdown-toggle user-info\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
          out.write("                                <i class=\"fas fa-user-circle\"></i> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.usuarioLogeado.nombreUsuario}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                            </a>\n");
          out.write("                            <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">\n");
          out.write("                                <li><a class=\"dropdown-item\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/perfil\"><i class=\"fas fa-cog me-1\"></i> Mi Cuenta</a></li>\n");
          out.write("                                <li><hr class=\"dropdown-divider\"></li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a class=\"dropdown-item text-danger\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout\">\n");
          out.write("                                        <i class=\"fas fa-sign-out-alt me-1\"></i> Cerrar Sesión\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                            </ul>\n");
          out.write("                        </li>\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        ");
          out.write("\n");
          out.write("                        <li class=\"nav-item\">\n");
          out.write("                            <a class=\"nav-link\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/registro\">\n");
          out.write("                                <i class=\"fas fa-user-plus\"></i> Registrarse\n");
          out.write("                            </a>\n");
          out.write("                        </li>\n");
          out.write("                        <li class=\"nav-item\">\n");
          out.write("                            <a class=\"nav-link\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\">\n");
          out.write("                                <i class=\"fas fa-sign-in-alt\"></i> Iniciar Sesión\n");
          out.write("                            </a>\n");
          out.write("                        </li>\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /jsp/includes/navbar.jspf(117,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.carritoCount and sessionScope.carritoCount > 0}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                            <span class=\"cart-badge\" id=\"cart-badge-count\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.carritoCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /jsp/includes/navbar.jspf(120,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.carritoCount or sessionScope.carritoCount == 0}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                            <span class=\"cart-badge d-none\" id=\"cart-badge-count\">0</span>\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /jsp/catalogo.jsp(235,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fforEach_005f0.setVar("producto");
      // /jsp/catalogo.jsp(235,16) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/catalogo.jsp(235,16) '${productos}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productos}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                    <div class=\"col\">\n");
            out.write("                        <div class=\"card product-card\">\n");
            out.write("                            <div class=\"product-image-wrapper\">\n");
            out.write("                                ");
            if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("\n");
            out.write("                                <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.codigo}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".png\" \n");
            out.write("                                     class=\"card-img-top\" \n");
            out.write("                                     alt=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.nombre}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\n");
            out.write("                                     onerror=\"this.src='");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/images/placeholder.png'\"/>\n");
            out.write("                            </div>\n");
            out.write("\n");
            out.write("                            <div class=\"card-body d-flex flex-column\">\n");
            out.write("                                <h5 class=\"product-name\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.nombre}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\n");
            out.write("                                <span class=\"product-category\">\n");
            out.write("                                    <i class=\"fas fa-tag\"></i> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.categoria}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("                                </span>\n");
            out.write("\n");
            out.write("                                <div class=\"mt-auto\">\n");
            out.write("                                    <span class=\"price-label\">Precio:</span>\n");
            out.write("                                    <h4 class=\"product-price\">\n");
            out.write("                                        ");
            if (_jspx_meth_fmt_005fsetLocale_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" \n");
            out.write("                                        ");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("                                    </h4>\n");
            out.write("\n");
            out.write("                                    ");
            if (_jspx_meth_c_005fchoose_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("\n");
            out.write("                                </div>\n");
            out.write("                            </div>\n");
            out.write("                        </div>\n");
            out.write("                    </div>\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("                                    ");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /jsp/catalogo.jsp(240,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.stock > 0}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                        <span class=\"stock-badge\">\n");
          out.write("                                            <i class=\"fas fa-check-circle\"></i> Disponible\n");
          out.write("                                        </span>\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                        <span class=\"stock-badge out-of-stock\">\n");
          out.write("                                            <i class=\"fas fa-times-circle\"></i> Agotado\n");
          out.write("                                        </span>\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fsetLocale_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:setLocale
    org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag _jspx_th_fmt_005fsetLocale_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag) _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag.class);
    boolean _jspx_th_fmt_005fsetLocale_005f0_reused = false;
    try {
      _jspx_th_fmt_005fsetLocale_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fsetLocale_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /jsp/catalogo.jsp(267,40) name = value type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_fmt_005fsetLocale_005f0.setValue("es_PE");
      int _jspx_eval_fmt_005fsetLocale_005f0 = _jspx_th_fmt_005fsetLocale_005f0.doStartTag();
      if (_jspx_th_fmt_005fsetLocale_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
      _jspx_th_fmt_005fsetLocale_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fsetLocale_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fsetLocale_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /jsp/catalogo.jsp(268,40) name = value type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.precio}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /jsp/catalogo.jsp(268,40) name = type type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_fmt_005fformatNumber_005f0.setType("currency");
      // /jsp/catalogo.jsp(268,40) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_fmt_005fformatNumber_005f0.setCurrencySymbol("S/ ");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                        ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("                                        ");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /jsp/catalogo.jsp(272,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.stock > 0}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                            <div class=\"d-flex gap-2\">\n");
          out.write("                                                <button type=\"button\" \n");
          out.write("                                                        class=\"btn btn-accent flex-grow-1 btn-comprar\"\n");
          out.write("                                                        onclick=\"agregarAlCarrito(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.idProducto}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(", this)\">\n");
          out.write("                                                    <i class=\"fas fa-shopping-bag\"></i> Comprar\n");
          out.write("                                                </button>\n");
          out.write("                                                <button type=\"button\" \n");
          out.write("                                                        class=\"btn btn-outline-secondary btn-icon-cart\" \n");
          out.write("                                                        onclick=\"agregarAlCarrito(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.idProducto}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(", this)\"\n");
          out.write("                                                        title=\"Agregar al carrito\">\n");
          out.write("                                                    <i class=\"fas fa-cart-plus\"></i>\n");
          out.write("                                                </button>\n");
          out.write("                                            </div>\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                            <button class=\"btn btn-secondary disabled w-100\" disabled>\n");
          out.write("                                                <i class=\"fas fa-ban\"></i> Sin Stock\n");
          out.write("                                            </button>\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /jsp/catalogo.jsp(301,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty productos}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    <div class=\"col-12\">\n");
          out.write("                        <div class=\"empty-state\">\n");
          out.write("                            <div class=\"empty-state-icon\">\n");
          out.write("                                <i class=\"fas fa-box-open\"></i>\n");
          out.write("                            </div>\n");
          out.write("                            <h3 class=\"empty-state-title\">No hay productos disponibles</h3>\n");
          out.write("                            <p class=\"empty-state-text\">\n");
          out.write("                                Lo sentimos, actualmente no tenemos productos en el catálogo.<br>\n");
          out.write("                                Vuelve pronto para ver nuestras novedades.\n");
          out.write("                            </p>\n");
          out.write("                        </div>\n");
          out.write("                    </div>\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
